// <auto-generated />
using System;
using DeliverITTestAPI.EFC;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeliverITTestAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221118220713_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("DeliverITTestAPI.Model.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DtDue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DtPayment")
                        .HasColumnType("TEXT");

                    b.Property<string>("NmBill")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NuDaysLate")
                        .HasColumnType("INTEGER");

                    b.Property<double>("VlCorrected")
                        .HasColumnType("REAL");

                    b.Property<double>("VlOriginal")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
